name: Integrationtest

on:
    push:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: 'Install Node'
          uses: actions/setup-node@v3
          with:
            node-version: '18.x'

        - name: 'Install Deps'
          run: npm install

        - name: 'Install playwright'
          run: npx playwright install

        - name: 'Integration test'
          run: npm run test:integration

